.PHONY: clean All

All:
	@echo "----------Building project:[ mybash - Debug ]----------"
	@"$(MAKE)" -f  "mybash.mk"
clean:
	@echo "----------Cleaning project:[ mybash - Debug ]----------"
	@"$(MAKE)" -f  "mybash.mk" clean
