.PHONY: clean All

All:
	@echo "----------Building project:[ slooping - Debug ]----------"
	@cd "slooping" && "$(MAKE)" -f  "slooping.mk"
clean:
	@echo "----------Cleaning project:[ slooping - Debug ]----------"
	@cd "slooping" && "$(MAKE)" -f  "slooping.mk" clean
